allprojects {
    repositories {
        google()
        mavenCentral()
    }

    // Exclude unwanted plugins to avoid Java version issue
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
